# Generated by Django 4.2 on 2023-08-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="api_tunnel",
            field=models.TextField(default=""),
        ),
    ]
